name: mt3-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - ffmpeg
  - pip:
    - "jax[cpu]==0.4.14"
    - tensorflow==2.12.0
    - tensorflow-datasets
    - seqio==0.0.19
    - clu==0.0.8
    - flax==0.7.2
    - gin-config
    - librosa
    - mir_eval
    - pretty_midi
    - absl-py
    - immutabledict
    - note-seq
    - git+https://github.com/google-research/t5x.git
    - t5
    - git+https://github.com/magenta/mt3.git
