name: mt3-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - scikit-learn
  - tensorflow
  - tensorflow-datasets
  - librosa
  - mir_eval
  - pretty_midi
  - absl-py
  - flax
  - gin-config
  - immutabledict
  - pip:
      - note-seq
      - seqio
      - t5
      - t5x
